# Generated by Django 5.2.8 on 2025-11-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitioTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_sitio', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('religioso', 'Religioso'), ('cultural', 'Cultural'), ('turistico', 'Turistico'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('etiquetas', models.CharField(blank=True, max_length=255, null=True)),
                ('pais', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=100, max_digits=200, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=100, max_digits=200, null=True)),
                ('capaciad', models.CharField(blank=True, null=True)),
                ('servicios_ofrecidos', models.CharField(blank=True, max_length=1000, null=True)),
                ('url_imagen_principal', models.URLField(blank=True, max_length=255, null=True)),
                ('galeria_imagenes', models.TextField(blank=True, null=True)),
                ('estado_publicacion', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], default='borrador', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
