# Generated by Django 5.2.8 on 2025-11-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_sitioturistico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitioturistico',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitioturistico',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
